remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Calorie Predictions]
description: [DSC80 Project 5]
description: [DSC80 Project 3 - https://vdubey0.github.io/RecipeAnalysis/]
